---
title: "ceciliaergueta_A5"
author: "Cecilia Ergueta"
date: "10/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warnings = F, message = F)

library(tidyverse)
library(censusapi)
library(sf)
library(tigris)
library(mapview)
library(readxl)

ces4 <- read_excel("calenviroscreen40resultsdatadictionary_F_2021.xlsx")

colnames(ces4)

ces4_clean <- ces4 %>% 
  dplyr::select(!ends_with("Pctl"))

sum(is.na(ces4_clean$Poverty))

ces4_clean %>% 
  # .$Poverty %>%
  pull(Poverty) %>% 
  is.na() %>% 
  sum()

ca_tracts <- tracts("CA")

ces4_map <- ces4_clean %>% 
  left_join(
    ca_tracts %>% 
      transmute(GEOID = GEOID %>% as.numeric()),
    by = c("Census Tract" = "GEOID")
  ) %>% 
  st_as_sf()

mapview(ces4_map, zcol = "Asthma")
## Comment: I noticed the highest asthma rates in Oakland.

mapview(ces4_map, zcol = "PM2.5")
## Comment: The rates of PM2.5 seemed pretty similar across the bay area, although slightly higher in Oakland.

```

```{r scatterplot}
#scatterplot:
ces4_scatterplot <- ggplot(
  data = ces4_clean,
  aes(
      x = PM2.5, 
      y = Asthma
    )
) +
#linear regression:
  geom_point() +
  geom_smooth(method = "lm")

ces4_scatterplot
```


